# **Task 2**
***Pivot Table***

**1. create a pivot table that shows the average LoanAmount for different EmploymentStatus and EducationLevel groups?**

**2. combination of MaritalStatus and RiskScore? How can you build a pivot table
to display the total MonthlyLoanPayment for each**

In [ ]:
import pandas as pd

In [ ]:
loan_df = pd.read_csv('/content/Loan.csv')
#ignore this head part
loan_df.head()

,ApplicationDate,Age,AnnualIncome,CreditScore,EmploymentStatus,EducationLevel,Experience,LoanAmount,LoanDuration,MaritalStatus,...,MonthlyIncome,UtilityBillsPaymentHistory,JobTenure,NetWorth,BaseInterestRate,InterestRate,MonthlyLoanPayment,TotalDebtToIncomeRatio,LoanApproved,RiskScore
0,2018-01-01,45,39948,617,Employed,Master,22,13152,48,Married,...,3329.000000,0.724972,11,126928,0.199652,0.227590,419.805992,0.181077,0,49.0
1,2018-01-02,38,39709,628,Employed,Associate,15,26045,48,Single,...,3309.083333,0.935132,3,43609,0.207045,0.201077,794.054238,0.389852,0,52.0
2,2018-01-03,47,40724,570,Employed,Bachelor,26,17627,36,Married,...,3393.666667,0.872241,6,5205,0.217627,0.212548,666.406688,0.462157,0,52.0
3,2018-01-04,58,69084,545,Employed,High School,34,37898,96,Single,...,5757.000000,0.896155,5,99452,0.300398,0.300911,1047.506980,0.313098,0,54.0
4,2018-01-05,37,103264,594,Employed,Associate,17,9184,36,Married,...,8605.333333,0.941369,5,227019,0.197184,0.175990,330.179140,0.070210,1,36.0

**How can you create a pivot table that shows the average LoanAmount for different EmploymentStatus and EducationLevel groups?**

In [ ]:
pivot_1 = loan_df.pivot_table(values='LoanAmount', index='EmploymentStatus', columns='EducationLevel', aggfunc='mean')
pivot_1

EducationLevel,Associate,Bachelor,Doctorate,High School,Master
EmploymentStatus,,,,,
Employed,24676.509714,24710.653915,25452.660000,25030.816960,24759.694874
Self-Employed,24407.858779,25331.991304,25206.837838,24504.514286,24413.364516
Unemployed,26168.562500,26445.619816,23179.333333,24891.980645,24554.872340

**combination of MaritalStatus and RiskScore? How can you build a pivot table
to display the total MonthlyLoanPayment for each**

In [ ]:
loan_df.pivot_table(values='MonthlyLoanPayment', index='HomeOwnershipStatus', columns='RiskScore', aggfunc='sum')

RiskScore,28.8,29.6,30.4,31.2,32.0,32.8,33.6,34.4,35.2,36.0,...,71.0,72.0,73.0,74.0,75.0,76.0,77.0,78.0,79.0,84.0
HomeOwnershipStatus,,,,,,,,,,,,,,,,,,,,,
Mortgage,3029.211807,1987.868881,1275.668718,3749.581780,8077.651125,10994.315782,26885.862954,33883.919060,58525.978353,51036.031768,...,8858.785390,11851.894005,7346.365378,5192.211049,1769.438379,1003.302283,515.836702,2841.551083,1049.971078,NaN
Other,251.369187,1829.847140,517.504367,571.062002,1909.820362,2646.853315,4519.289035,3901.641048,11352.543808,11414.570345,...,1658.034928,NaN,NaN,399.196907,1039.562739,561.575725,NaN,356.763438,NaN,684.709064
Own,NaN,1926.543982,1399.097360,2902.982452,2889.337012,11376.497287,17866.460773,26319.309873,25587.629484,33177.085282,...,4009.796837,6326.414195,3676.146450,586.166407,319.794220,NaN,678.880708,NaN,497.157112,NaN
Rent,1555.118579,NaN,2451.162612,8833.840765,12990.038728,13508.201189,19512.155914,22352.218806,39205.567602,54963.225189,...,7414.027471,7138.242522,8093.068980,1529.207507,1585.638054,2389.838072,919.060521,NaN,1337.695804,NaN